// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Peer struct {
	ID          int64
	PublicKey   string
	Name        *string
	TrackStats  bool
	FirstSeen   pgtype.Timestamptz
	LastSeen    pgtype.Timestamptz
	LastRxBytes int64
	LastTxBytes int64
	AllowedIps  string
}

type PeerSnapshot struct {
	ID              int64
	PeerID          int64
	Ts              pgtype.Timestamptz
	Endpoint        *string
	LatestHandshake pgtype.Timestamptz
	RxBytes         int64
	TxBytes         int64
	RxDelta         int64
	TxDelta         int64
}
