// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertSnapshot = `-- name: InsertSnapshot :exec
INSERT INTO peer_snapshots
    (peer_id, ts, endpoint, latest_handshake, rx_bytes, tx_bytes, rx_delta, tx_delta)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertSnapshotParams struct {
	PeerID          int64
	Ts              pgtype.Timestamptz
	Endpoint        *string
	LatestHandshake pgtype.Timestamptz
	RxBytes         int64
	TxBytes         int64
	RxDelta         int64
	TxDelta         int64
}

func (q *Queries) InsertSnapshot(ctx context.Context, arg InsertSnapshotParams) error {
	_, err := q.db.Exec(ctx, insertSnapshot,
		arg.PeerID,
		arg.Ts,
		arg.Endpoint,
		arg.LatestHandshake,
		arg.RxBytes,
		arg.TxBytes,
		arg.RxDelta,
		arg.TxDelta,
	)
	return err
}

const setPeerTracking = `-- name: SetPeerTracking :exec
UPDATE peers SET track_stats = $2 WHERE public_key = $1
`

type SetPeerTrackingParams struct {
	PublicKey  string
	TrackStats bool
}

// Включить/выключить запись статистики для пира вручную (peer_snapshots не
// пишется, если track_stats = false).
func (q *Queries) SetPeerTracking(ctx context.Context, arg SetPeerTrackingParams) error {
	_, err := q.db.Exec(ctx, setPeerTracking, arg.PublicKey, arg.TrackStats)
	return err
}

const updatePeerCounters = `-- name: UpdatePeerCounters :exec
UPDATE peers SET last_rx_bytes = $2, last_tx_bytes = $3 WHERE id = $1
`

type UpdatePeerCountersParams struct {
	ID          int64
	LastRxBytes int64
	LastTxBytes int64
}

func (q *Queries) UpdatePeerCounters(ctx context.Context, arg UpdatePeerCountersParams) error {
	_, err := q.db.Exec(ctx, updatePeerCounters, arg.ID, arg.LastRxBytes, arg.LastTxBytes)
	return err
}

const upsertPeer = `-- name: UpsertPeer :one
INSERT INTO peers (public_key, first_seen, last_seen)
VALUES ($1, now(), now())
ON CONFLICT (public_key) DO UPDATE SET last_seen = now()
RETURNING id, track_stats, last_rx_bytes, last_tx_bytes
`

type UpsertPeerRow struct {
	ID          int64
	TrackStats  bool
	LastRxBytes int64
	LastTxBytes int64
}

func (q *Queries) UpsertPeer(ctx context.Context, publicKey string) (UpsertPeerRow, error) {
	row := q.db.QueryRow(ctx, upsertPeer, publicKey)
	var i UpsertPeerRow
	err := row.Scan(
		&i.ID,
		&i.TrackStats,
		&i.LastRxBytes,
		&i.LastTxBytes,
	)
	return i, err
}
